// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo0k7-_le7AtSWb_e0IzQ8tMtjmBuGH-k',
    appId: '1:597409554991:web:30de8e5bd1719390f45cda',
    messagingSenderId: '597409554991',
    projectId: 'versanteventreports-2d0ee',
    authDomain: 'versanteventreports-2d0ee.firebaseapp.com',
    storageBucket: 'versanteventreports-2d0ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV77ouNnBMm-0ilaN5TAhzxEoEKqOTyH4',
    appId: '1:597409554991:android:f2649dbb98ad58ecf45cda',
    messagingSenderId: '597409554991',
    projectId: 'versanteventreports-2d0ee',
    storageBucket: 'versanteventreports-2d0ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5h7ni2xvwf-5d_mUXYRzJ8sLGLIlWgo8',
    appId: '1:597409554991:ios:0bb6cefdfd0a0e67f45cda',
    messagingSenderId: '597409554991',
    projectId: 'versanteventreports-2d0ee',
    storageBucket: 'versanteventreports-2d0ee.firebasestorage.app',
    iosBundleId: 'com.typhenebenfriha.versantEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5h7ni2xvwf-5d_mUXYRzJ8sLGLIlWgo8',
    appId: '1:597409554991:ios:3012a71d39b81645f45cda',
    messagingSenderId: '597409554991',
    projectId: 'versanteventreports-2d0ee',
    storageBucket: 'versanteventreports-2d0ee.firebasestorage.app',
    iosBundleId: 'com.versanteventapp.versantEvent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo0k7-_le7AtSWb_e0IzQ8tMtjmBuGH-k',
    appId: '1:597409554991:web:5ca3fbf761a90babf45cda',
    messagingSenderId: '597409554991',
    projectId: 'versanteventreports-2d0ee',
    authDomain: 'versanteventreports-2d0ee.firebaseapp.com',
    storageBucket: 'versanteventreports-2d0ee.firebasestorage.app',
  );
}
